# Changes here will be overwritten by Copier
_commit: 1a45ad8
_src_path: gh:audivir/copier-template
description: Watches memory usage of a process and terminates it if a limit is exceeded
github_org: audivir
go_module_path: github.com/audivir/memlimit
go_version: '1.26'
project_name: memlimit
project_slug: memlimit
project_type: go
publishable: true
